//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorkoutsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int IdContract { get; set; }
        public int IdUser { get; set; }
        public int NumberPremiumWork { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual Premium_Works Premium_Works { get; set; }
        public virtual Users Users { get; set; }
    }
}
