//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorkoutsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercises()
        {
            this.WorkoutElements = new HashSet<WorkoutElements>();
        }
    
        public int ID_Exercise { get; set; }
        public string Name_Exercise { get; set; }
        public string Description_Exercise { get; set; }
        public int Duration_Exercise { get; set; }
        public Nullable<int> Type_Exercise { get; set; }
        public Nullable<int> Premium_Work_Number { get; set; }
        public string PicturePath { get; set; }
    
        public virtual Premium_Works Premium_Works { get; set; }
        public virtual Types_Workout Types_Workout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutElements> WorkoutElements { get; set; }
    }
}
