//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorkoutsWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartWorkouts_newEntities : DbContext
    {
        public SmartWorkouts_newEntities()
            : base("name=SmartWorkouts_newEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exercises> Exercises { get; set; }
        public virtual DbSet<FavouritePosts> FavouritePosts { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Premium_Works> Premium_Works { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Types_Workout> Types_Workout { get; set; }
        public virtual DbSet<User_Progress> User_Progress { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkoutElements> WorkoutElements { get; set; }
        public virtual DbSet<Workouts> Workouts { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<BuildID> BuildID { get; set; }
    }
}
