//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWorkoutsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Progress
    {
        public int ID_Progress { get; set; }
        public int User_ID { get; set; }
        public decimal StartWeight { get; set; }
        public decimal CurrentWeight { get; set; }
        public decimal DesiredWeight { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
